Add a "Save statistics"
dakra/speed-type pull request #42
Opened 2023-10-04 08:18 UTC by platoali

This patch. add "save" option to the speed-type. User have the option to save the statistics automatically, ask before saving or never save. 

The are configurations  that give user   options where to save the records, maximum number of records to save. 

I am new to programming and lisp. probably there  are rough edges and bugs. Please  tell me how to improve this patch.

2023-10-11 09:32 UTC, dakra requested changes
Thank you very much.

I'll probably take a while to review this as I'm pretty busy atm.
But I had a very brief look and noted some superficial things.

But thanks for trying to tackle this, I wanted to have saved statistics since a while,
see https://github.com/dakra/speed-type/issues/11

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> -;;; speed-type.el --- Practice touch and speed typing -*- lexical-binding: t -*-
Removed by accident?

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +(require 'parse-csv)
Add an empty line after the require block

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +(defcustom speed-type-min-chars  10 ;;200
Left over from debugging?

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +(defcustom speed-type-max-chars 14 ;; 450
Left over from debugging?

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +
whitespace

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +  )
Group the closing parenthesis together.
Same below in other functions.

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +           (ggo-next-fn (lambda ()
Renamed by accident?

2023-10-11 09:32 UTC, dakra commented on speed-type.el
> +
Empty lines

2023-10-16 21:45 UTC, platoali commented on speed-type.el
> -;;; speed-type.el --- Practice touch and speed typing -*- lexical-binding: t -*-
yes

2023-10-16 21:46 UTC, platoali commented on speed-type.el
> +(defcustom speed-type-min-chars  10 ;;200
Yes. I have forget. to change it back.

2023-10-16 21:46 UTC, platoali commented on speed-type.el
> +
yes. I had to change it back before requesting. 
Sorry.

2023-10-16 21:47 UTC, platoali commented on speed-type.el
> +           (ggo-next-fn (lambda ()
yes

2023-10-16 21:48 UTC, platoali commented on speed-type.el
> +  )
Yes, you are correct.

2023-10-16 21:50 UTC, platoali commented on speed-type.el
> +
Thank you. Sorry I was not familiar with these conducts.

2025-02-18 22:16 UTC, lordnik22 commented
Storing speed-type session in file and median calculation got implemented with https://github.com/dakra/speed-type/pull/46

2025-02-18 22:16 UTC, closed without merging